[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "rotcurves"
version = "0.1.0"
authors = [
  { name="Amit Nestor Shachar", email="amit.nestorr@gmail.com" },
]
description = "A short description of your package"
readme = "README.md"
requires-python = ">=3.7"
license = { text = "LICENSE" }
dependencies = [
  "numpy",
  "pandas",
]
keywords = ["astrophysics", "galaxy", "rotation curve"]

[project.urls]
"Homepage" = "https://github.com/nestoramit/RotCurves"
"Bug Tracker" = "https://github.com/nestoramit/RotCurves/issues"